version: 0.2
env:
  variables:
    ECR_REPO: 727646491714.dkr.ecr.us-east-1.amazonaws.com/lks-order-image
    ECR_REGION: us-east-1
    CONTAINER_NAME: order
phases:
  install:
    runtime-versions:
      nodejs: 16
      docker: 20
  pre_build:
    commands:
      - echo "Install Dependencies and login into ECR"
      - $(aws ecr get-login --no-include-email --region $ECR_REGION)
  build:
    commands:
      - echo "Run unit testing and build docker image"
      - docker build -t $CONTAINER_NAME:latest .
  post_build:
    commands:
      - echo "Push the image to ECR..."
      # Tagging the image with build number
      - docker tag $CONTAINER_NAME:latest $ECR_REPO:latest
      - docker tag $CONTAINER_NAME:latest $ECR_REPO:${CODEBUILD_BUILD_NUMBER}
      - docker push $ECR_REPO:latest
      - docker push $ECR_REPO:${CODEBUILD_BUILD_NUMBER}
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $ECR_REPO:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
